/*
 * AMIT_7_SEGMENT.c
 *
 * Created: 5/11/2019 10:16:15 PM
 *  Author: hp
 */ 
#include "AMIT_7_SEGMENT.h"
extern void SEGMENT_DISPLAY_NUM(unsigned int Num)
{
	DIO_pinOUT(AMIT_DDR_SEGMENT_ENABLE1,AMIT_PIN_SEGMENT_ENABLE1);
	DIO_pinOUT(AMIT_DDR_SEGMENT_ENABLE2,AMIT_PIN_SEGMENT_ENABLE2);
	DIO_pinOUT(AMIT_DDR_SEGMENT_A,AMIT_PIN_SEGMENT_A);
	DIO_pinOUT(AMIT_DDR_SEGMENT_B,AMIT_PIN_SEGMENT_B);
	DIO_pinOUT(AMIT_DDR_SEGMENT_C,AMIT_PIN_SEGMENT_C);
	DIO_pinOUT(AMIT_DDR_SEGMENT_D,AMIT_PIN_SEGMENT_D);
	
	if (Num < 10)
	{
		DIO_pinWRITE(AMIT_PORT_SEGMENT_ENABLE1,AMIT_PIN_SEGMENT_ENABLE1,1);
		DIO_pinWRITE(AMIT_PORT_SEGMENT_ENABLE2,AMIT_PIN_SEGMENT_ENABLE2,0);
		DIO_pinWRITE(AMIT_PORT_SEGMENT_A,AMIT_PIN_SEGMENT_A,Num & 0x1);
		DIO_pinWRITE(AMIT_PORT_SEGMENT_B,AMIT_PIN_SEGMENT_B,Num & 0x2);
		DIO_pinWRITE(AMIT_PORT_SEGMENT_C,AMIT_PIN_SEGMENT_C,Num & 0x4);
		DIO_pinWRITE(AMIT_PORT_SEGMENT_D,AMIT_PIN_SEGMENT_D,Num & 0x8);
	}
}
